package com.studio.constants;

public class Queries {
	public static String CREATE_USER_DETAILS = "INSERT INTO USERS(UID,NAME,EMAIL,CONTACT,ROLE,STATUS,CREATEDBY,CREATEDON) values (?,?,?,?,?,?,?,?);";
	public static String CREATE_USER_LOGON = "INSERT INTO LOGON (UID,PSWD,SALT,CREATEDBY,CREATEDON) VALUES(?,?,?,?,?);";
	//public static String STORE_PASSWORD = "INSERT INTO LOGON (UID,PSWD,SALT,CREATEDBY) VALUES(?,?,?,?);";
	public static String IS_USER_AUTHORIZED = "SELECT * FROM LOGON WHERE UID=upper(?) AND DELETEDBY IS NULL and DELETEDON IS NULL;";
	public static String UPDATE_LAST_LOGIN = "UPDATE USERS SET LASTLOGINAT=? WHERE UID=?";
	public static String READ_LAST_LOGIN = "SELECT LASTLOGINAT FROM USERS WHERE UID=?";
	public static String READ_USER_DETAILS = "SELECT * FROM USERS WHERE UID=?";
	public static String READ_LASTLOGIN_ISPSWD_DEFAULT="SELECT LASTLOGINAT,ISPSWDDEFAULT FROM USERS LEFT JOIN LOGON ON USERS.UID=LOGON.UID where USERS.UID=?;";
	
	public static String LOAD_ALL_USER_DETAILS="SELECT U.UID,U.NAME, U.EMAIL, U.CONTACT,U.CREATEDON, U.CREATEDBY,U.UPDATEDON, U.UPDATEDBY, U.DELETEDON, U.DELETEDBY, U.LASTLOGINAT, U.ROLE, U.STATUS,U.PSWDCHANGEDBY,U.PSWDCHANGEDON, R.RNAME FROM USERS U LEFT JOIN ROLES R ON U.ROLE=R.RID;";
	public static String LOAD_USER_ROLE="SELECT ROLE FROM USERS WHERE UID=? AND STATUS='Y' AND DELETEDON IS NULL AND DELETEDBY IS NULL";
	public static String LOAD_USER_DETAILS="SELECT U.UID,U.NAME, U.EMAIL, U.CONTACT,U.CREATEDON, U.CREATEDBY,U.UPDATEDON, U.UPDATEDBY, U.DELETEDON, U.DELETEDBY, U.LASTLOGINAT, U.ROLE, U.STATUS, R.RNAME FROM USERS U LEFT JOIN ROLES R ON U.ROLE=R.RID WHERE U.UID=?;";
	public static String LOAD_ALL_ROLES="SELECT * FROM ROLES ORDER BY RID ASC";
	public static String LOAD_ALL_BILLS_DATA="SELECT * FROM BILLS ORDER BY BILLID ASC";
	
	public static String LOAD_ALL_PHOTOS_PRINT_MASTER_DATA="SELECT * FROM PHOTOS_PRINT_MASTER_DATA ORDER BY PHOTOID ASC";
	public static String LOAD_ALL_FRAME_MASTER_DATA="SELECT * FROM FRAME_MASTER_DATA ORDER BY FRAMEID ASC";
	public static String LOAD_ALL_MIRROR_MASTER_DATA="SELECT * FROM MIRROR_MASTER_DATA ORDER BY MIRRORID ASC";
	
	public static String INSERT_NEW_FRAME_RECORD = "INSERT INTO FRAME_MASTER_DATA(DESCRIPTION,QUANTITY,PRICE,CREATEDBY) VALUES(?,?,?,?);";
	public static String INSERT_NEW_MIRROR_RECORD = "INSERT INTO MIRROR_MASTER_DATA(DESCRIPTION,QUANTITY,PRICE,CREATEDBY) VALUES(?,?,?,?);";
	public static String INSERT_NEW_PHOTOS_PRINT_RECORD = "INSERT INTO PHOTOS_PRINT_MASTER_DATA(DESCRIPTION,QUANTITY,PRICE,CREATEDBY) VALUES(?,?,?,?);";
	public static String INSERT_NEW_LOGON_RECORD = "INSERT INTO LOGON(UID,Pswd,Salt,createdby,createdon) VALUES(?,?,?,?,?);";
	public static String INSERT_NEW_USERS_RECORD = "INSERT INTO USERS(UID,NAME,EMAIL,CONTACT,ROLE,STATUS,CREATEDON,CREATEDBY) VALUES(?,?,?,?,?,?,?,?);";
	
	public static String DELETE_FRAME_RECORD = "UPDATE FRAME_MASTER_DATA SET DELETEDON=?,DELETEDBY=? WHERE FRAMEID=?";
	public static String DELETE_MIRROR_RECORD = "UPDATE MIRROR_MASTER_DATA SET DELETEDON=?,DELETEDBY=? WHERE MIRRORID=?";
	public static String DELETE_PHOTOS_PRINT_RECORD = "UPDATE PHOTOS_PRINT_MASTER_DATA SET DELETEDON=?,DELETEDBY=? WHERE PHOTOID=?";
	public static String DELETE_USERS_RECORD = "UPDATE USERS SET DELETEDON=?,DELETEDBY=? WHERE UID=?";
	public static String DELETE_LOGON_RECORD = "UPDATE LOGON SET DELETEDON=?,DELETEDBY=? WHERE UID=?";
		
	public static String RECREATE_FRAME_RECORD = "UPDATE FRAME_MASTER_DATA SET UPDATEDBY=?,UPDATEDON=?,DELETEDBY=NULL,DELETEDON=NULL WHERE FRAMEID=?";
	public static String RECREATE_MIRROR_RECORD = "UPDATE MIRROR_MASTER_DATA SET UPDATEDBY=?,UPDATEDON=?,DELETEDBY=NULL,DELETEDON=NULL WHERE MIRRORID=?";
	public static String RECREATE_PHOTOS_PRINT_RECORD = "UPDATE PHOTOS_PRINT_MASTER_DATA SET UPDATEDBY=?,UPDATEDON=?,DELETEDBY=NULL,DELETEDON=NULL WHERE PHOTOID=?";
	public static String RECREATE_USERS_RECORD = "UPDATE USERS SET UPDATEDBY=?,UPDATEDON=?,DELETEDBY=NULL,DELETEDON=NULL WHERE UID=?";
	public static String RECREATE_LOGON_RECORD = "UPDATE LOGON SET UPDATEDBY=?,UPDATEDON=?,DELETEDBY=NULL,DELETEDON=NULL WHERE UID=?";
	
	
	public static String UPDATE_FRAME_RECORD = "UPDATE FRAME_MASTER_DATA SET DESCRIPTION=?,QUANTITY=?,PRICE=?,UPDATEDBY=?,UPDATEDON=? WHERE FRAMEID=?";
	public static String UPDATE_MIRROR_RECORD = "UPDATE MIRROR_MASTER_DATA SET DESCRIPTION=?,QUANTITY=?,PRICE=?,UPDATEDBY=?,UPDATEDON=? WHERE MIRRORID=?";
	public static String UPDATE_PHOTOS_PRINT_RECORD = "UPDATE PHOTOS_PRINT_MASTER_DATA SET DESCRIPTION=?,QUANTITY=?,PRICE=?,UPDATEDBY=?,UPDATEDON=? WHERE PHOTOID=?";
	public static String UPDATE_USERS_STATUS_RECORD = "UPDATE USERS SET STATUS=?,UPDATEDBY=?,UPDATEDON=? WHERE UID=?";
	public static String UPDATE_USERS_RECORD = "UPDATE USERS SET NAME=?,EMAIL=?,CONTACT=?,ROLE=?,UPDATEDON=?,UPDATEDBY=? WHERE UID = ?;";
	public static String UPDATE_LOGON_RECORD="UPDATE LOGON SET PSWD = ?, SALT = ?, UPDATEDBY = ?, UPDATEDON = ?,ISPSWDDEFAULT=0 WHERE UID = ?;";
	public static String UPDATE_USER_CHANGE_PASSWORD="UPDATE USERS SET UPDATEDBY = ?, UPDATEDON = ?, PSWDCHANGEDBY=?,PSWDCHANGEDON=? WHERE UID = ?;";
	
	public static String FETCH_FRAMEID = "SELECT * FROM FRAME_MASTER_DATA WHERE ID=?";
	public static String FETCH_MIRRORID= "SELECT * FROM MIRROR_MASTER_DATA WHERE ID=?";
	public static String FETCH_PHOTOSID = "SELECT * FROM PHOTOS_PRINT_MASTER_DATA WHERE ID=?";
	public static String FETCH_BILLID = "SELECT BILLID FROM BILLS WHERE ID=?";
	
	public static String UPDATE_LOGON_RECORD_TEMP_PSWD="UPDATE LOGON SET PSWD = ?, SALT = ?,ISPSWDDEFAULT=1, UPDATEDBY = ?, UPDATEDON = ? WHERE UID = ?;";
	public static String INSERT_NEW_BILL = "INSERT INTO BILLS(CUSTNAME,MOBILENO,EMAIL,DISCOUNT,FINAL_BILL_PRICE,ADVANCE,DELIVERY_DATE,DELIVERY_STATUS,createdby,createdon)VALUES(?,?,?,?,?,?,?,?,?,?)";
	public static String INSERT_NEW_ITEM = "INSERT INTO ITEMS(ITEMID,BILLID,CREATEDON,CREATEDBY) VALUES(?,?,?,?)";
	public static String LOAD_BILLS_OVERVIEW = "SELECT * FROM BILLS";
	public static String LOAD_ITEMS_OVERVIEW = "SELECT * FROM ITEMS I LEFT JOIN FRAME_MASTER_DATA F ON (CASE WHEN I.ITEMID LIKE 'FR%' THEN I.ITEMID ELSE NULL END) = F.FRAMEID LEFT JOIN MIRROR_MASTER_DATA M ON (CASE WHEN I.ITEMID LIKE 'MR%' THEN I.ITEMID ELSE NULL END) = M.MIRRORID LEFT JOIN PHOTOS_PRINT_MASTER_DATA P ON (CASE WHEN I.ITEMID LIKE 'PH%' THEN I.ITEMID ELSE NULL END) = P.PHOTOID WHERE (F.FRAMEID IS NOT NULL OR M.MIRRORID IS NOT NULL OR P.PHOTOID IS NOT NULL) AND I.BILLID=?";
}
